name: octopus
description: Simple expense tracking app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.4
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  intl: ^0.18.1
  equatable: ^2.0.5
  go_router: ^13.2.4

  auth_repository:
    path: packages/auth_repository
  auth_api:
    path: packages/auth_api

  data_repository:
    path: packages/data_repository
  data_api:
    path: packages/data_api

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
