name: auth_api
description: The interface and models for an API providing user authentication.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  equatable: ^2.0.5
  fpdart: ^1.1.0
  meta: ^1.11.0

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^5.1.0

