name: auth_api
description: The interface and models for an API providing user authentication.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  rxdart: ^0.27.7
  meta: ^1.11.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  firebase_auth_mocks: ^0.13.0
