name: firebase_auth_api
description: A Flutter implementation of the AuthApi that uses firebase.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  auth_api:
    path: ../auth_api
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  rxdart: ^0.27.7
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  firebase_auth_mocks: ^0.13.0
