name: repository_user
description: A repository that handles user lifecycle related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  api_auth:
    path: ../api_auth
  api_data:
    path: ../api_data
  equatable: ^2.0.3
  meta: ^1.7.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
