name: firebase_data_api
description: A Flutter implementation of the DataApi that uses firebase cloud firestore.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  data_api:
    path: ../data_api
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
