name: api_data_firestore
description: A Flutter implementation of the DataAPI that uses google cloud firestore.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  api_data:
    path: ../api_data
  cloud_firestore: ^4.17.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
