name: api_data
description: The interface and models for an API providing access to database storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.8.0
  meta: ^1.7.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.3.3  
  json_serializable: ^6.6.0
  test: ^1.25.2
  very_good_analysis: ^5.1.0
